heroku_server/server/goshop/config/routes.rb
Goshop::Application.routes.draw do
  resources :recommendations

  resources :products
  
  resources :categories do
    resources :products do
      resources :recommendations
    end
  end

end

heroku_server/server/goshop/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

heroku_server/server/goshop/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :recommendations
end

heroku_server/server/goshop/app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :product
end

heroku_server/server/goshop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

heroku_server/server/goshop/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  respond_to :json, :xml
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

heroku_server/server/goshop/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  respond_to :json, :xml
  def index
    if params[:category_id]
      @products = Product.find_all_by_category_id(params[:category_id])      
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end
end

heroku_server/server/goshop/app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  respond_to :json, :xml
  
  # GET /recommendations
  # GET /recommendations.json
  def index
    if params[:product_id]
      @recommendations = Recommendation.find_all_by_product_id(params[:product_id])
    else
      num = 10
      if params[:limit_num]
        num = params[:limit_num]
      end
      @recommendations = Recommendation.order("id DESC").limit(num)
    end
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recommendation }
    end
  end
  
  # def create_recommendations
  #   if params[:recommendation]
  #     @recommendation = Recommendation.new(params[:recommendation])
  #   end
  #   
  # end
  
  # GET /recommendations/new
  # GET /recommendations/new.json
  def new
    @recommendation = Recommendation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recommendation }
    end
  end

  # GET /recommendations/1/edit
  def edit
    @recommendation = Recommendation.find(params[:id])
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    if params[:message] && !params[:product_id]
      @recommendation = Recommendation.new(:message => params[:message], :rate => params[:rate].to_i, :url => params[:url])
    elsif params[:product_id]
      @recommendation = Recommendation.new(:message => params[:message], :rate => params[:rate].to_i, :url => params[:url], :product_id => params[:product_id])
    end
    

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully created.' }
        format.json { render json: @recommendation, status: :created, location: @recommendation }
      else
        format.html { render action: "new" }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recommendations/1
  # PUT /recommendations/1.json
  def update
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      if @recommendation.update_attributes(params[:recommendation])
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy

    respond_to do |format|
      format.html { redirect_to recommendations_url }
      format.json { head :ok }
    end
  end
end

heroku_server/server/goshop/app/helpers/application_helper.rb
module ApplicationHelper
end

heroku_server/server/goshop/app/helpers/categories_helper.rb
module CategoriesHelper
end

heroku_server/server/goshop/app/helpers/products_helper.rb
module ProductsHelper
end

heroku_server/server/goshop/app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

heroku_server/server/goshop/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

heroku_server/server/goshop/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

heroku_server/server/goshop/app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.number %></td>
	<td><%= link_to 'products', category_products_path(category) %></td>
    <td><%#= link_to 'Edit', edit_category_path(category) %></td>
    <td><%#= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Category', new_category_path %>

heroku_server/server/goshop/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

heroku_server/server/goshop/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Number:</b>
  <%= @category.number %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

heroku_server/server/goshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goshop</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

heroku_server/server/goshop/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :item_price %><br />
    <%= f.text_field :item_price %>
  </div>
  <div class="field">
    <%= f.label :saving %><br />
    <%= f.text_field :saving %>
  </div>
  <div class="field">
    <%= f.label :price_valid %><br />
    <%= f.text_field :price_valid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

heroku_server/server/goshop/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

heroku_server/server/goshop/app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Item price</th>
    <th>Saving</th>
    <th>Price valid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.item_price %></td>
    <td><%= product.saving %></td>
    <td><%= product.price_valid %></td>
    <td><%#= link_to 'Show', product %></td>
    <td><%#= link_to 'Edit', edit_product_path(product) %></td>
    <td><%#= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Product', new_product_path %>

heroku_server/server/goshop/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

heroku_server/server/goshop/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Item price:</b>
  <%= @product.item_price %>
</p>

<p>
  <b>Saving:</b>
  <%= @product.saving %>
</p>

<p>
  <b>Price valid:</b>
  <%= @product.price_valid %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

heroku_server/server/goshop/app/views/recommendations/_form.html.erb
<%= form_for(@recommendation) do |f| %>
  <% if @recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% @recommendation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.number_field :rate %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

heroku_server/server/goshop/app/views/recommendations/edit.html.erb
<h1>Editing recommendation</h1>

<%#= render 'form' %>

<%#= link_to 'Show', @recommendation %> |
<%#= link_to 'Back', recommendations_path %>

heroku_server/server/goshop/app/views/recommendations/index.html.erb
<h1>Listing recommendations</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Rate</th>
    <th>Message</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recommendations.each do |recommendation| %>
  <tr>
    <td><%= recommendation.product_id %></td>
    <td><%= recommendation.rate %></td>
    <td><%= recommendation.message %></td>
    <td><%= recommendation.url %></td>
    <td><%#= link_to 'Show', recommendation %></td>
    <td><%#= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
    <td><%#= link_to 'Destroy', recommendation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Recommendation', new_recommendation_path %>

heroku_server/server/goshop/app/views/recommendations/new.html.erb
<h1>New recommendation</h1>

<%#= render 'form' %>

<%#= link_to 'Back', recommendations_path %>

heroku_server/server/goshop/app/views/recommendations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @recommendation.product_id %>
</p>

<p>
  <b>Rate:</b>
  <%= @recommendation.rate %>
</p>

<p>
  <b>Message:</b>
  <%= @recommendation.message %>
</p>

<p>
  <b>Url:</b>
  <%= @recommendation.url %>
</p>


<%#= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
<%#= link_to 'Back', recommendations_path %>